PRN221PE_SU23_TrialTest_TranMinhThien/AuthorInstitution_TranMinhThien/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AuthorInstitution_TranMinhThien.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PRN221PE_SU23_TrialTest_TranMinhThien/AuthorInstitution_TranMinhThien/Pages/Login.cshtml.cs
using DataAccessObject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;
using Repository.Repo;

namespace AuthorInstitution_TranMinhThien.Pages
{
    public class LoginModel : PageModel
    {
        IAuthorInstitutionRepo _authorInstitutionRepo = new AuthorInstitutionRepo();

        [BindProperty]
        public MemberAccount MemberAccount { get; set; } = default!;

        public IActionResult OnPostLogin()
        {
            MemberAccount? loginAccount = _authorInstitutionRepo.Login(MemberAccount.MemberId, MemberAccount.MemberPassword);
            if (loginAccount == null)
            {
                ViewData["notification"] = "Email or Password is wrong!";
                return Page();
            }
            else
            if (loginAccount.MemberRole == 1)
            {
                HttpContext.Session.SetString("User", loginAccount.MemberId);
                return RedirectToPage("./Manage/Index");
            }
            else
            {
                ViewData["notification"] = "You do not have permission to do this function!";
                return Page();
            }

        }
        public IActionResult OnPostLogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Login");
        }

    }
}

PRN221PE_SU23_TrialTest_TranMinhThien/AuthorInstitution_TranMinhThien/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AuthorInstitution_TranMinhThien.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PRN221PE_SU23_TrialTest_TranMinhThien/AuthorInstitution_TranMinhThien/Pages/Login.cshtml
@page
@model AuthorInstitution_TranMinhThien.Pages.LoginModel
@{
}

<div class="container">
    <h1 class="text-center">Login</h1>
    <form method="post" class="my-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="MemberAccount.MemberId" class="control-label">Member Id</label>
            <input asp-for="MemberAccount.MemberId" class="form-control" required="true" />
            <span asp-validation-for="MemberAccount.MemberId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MemberAccount.MemberPassword" class="control-label">Password</label>
            <input asp-for="MemberAccount.MemberPassword" class="form-control" required="true" type="password" />
            <span asp-validation-for="MemberAccount.MemberPassword" class="text-danger"></span>
        </div>
        <div class="form-group text-danger">
            @ViewData["notification"]
        </div>
        <div class="form-group text-center">
            <button method="post" asp-page-handler="login" type="submit" class="btn btn-primary">Login</button>
        </div>
    </form>
</div>

PRN221PE_SU23_TrialTest_TranMinhThien/AuthorInstitution_TranMinhThien/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - AuthorInstitution_TranMinhThien</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/AuthorInstitution_TranMinhThien.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">AuthorInstitution_TranMinhThien</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <form method="post" asp-page-handler="LogOut" asp-page="/Login">
                            <button type="submit">Log out</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - AuthorInstitution_TranMinhThien - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>